version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    ports:
      - ${HOST_PORT}:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - app

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    volumes:
      - ./run/var:/var/lib/mysql
      - ./run/dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=fiUhjfE68dwhJb2Q1
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysql-db

networks:
  backend:
    name: backend-network
